_target_: model.sam.SAM
checkpoint_path: ./Instance_Segmentation_Model/checkpoints/SAM/sam_b.pt  # Ultralytics SAM Base模型
segmentor_width_size: ${model.segmentor_width_size}
config:
  iou_threshold: 0.9
  conf_threshold: 0.05
  max_det: 200